sound/misc/apito.wav
sound/misc/apito2.wav
sound/misc/Awwcrap.wav 
sound/misc/awwcrap2.wav
sound/misc/awwman.wav
sound/misc/Bleeeat.wav
sound/misc/chicken0.wav
sound/misc/chicken1.wav
sound/misc/chicken2.wav
sound/misc/chicken3.wav
sound/misc/chicken4.wav
sound/misc/comeagain.wav
sound/misc/cow.wav
sound/misc/cracker1.wav
sound/misc/doh.wav
sound/misc/dohoo.wav
sound/misc/dominating.wav
sound/misc/doublekill.wav
sound/misc/firstblood.wav
sound/misc/godlike.wav
sound/misc/headshot.wav
sound/misc/humiliation.wav
sound/misc/kenny1.wav
sound/misc/kickass1.wav
sound/misc/killChicken.wav
sound/misc/killingspree.wav
sound/misc/monsterkill.wav
sound/misc/multikill.wav
sound/misc/nam1.wav
sound/misc/Ow.wav
sound/misc/perfect.wav
sound/misc/plane_drone.wav
sound/misc/prepare.wav
sound/misc/rampage.wav
sound/misc/revenge1.wav
sound/misc/sheep.wav
sound/misc/shot1.wav
sound/misc/talk.wav
sound/misc/tick_tock_1b.wav
sound/misc/tick_tock_2b.wav
sound/misc/tick_tock_3b.wav
sound/misc/ultrakill.wav
sound/misc/unstoppable.wav
sound/misc/usc.wav
sound/misc/woohoo2.wav
maps/aim_ak-colt.res
maps/default.txt