maps/deathrun_barbie_csbr.bsp
maps/deathrun_barbie_csbr.txt
models/deathrun_barbie_csbr/barbiedancer.mdl
models/deathrun_barbie_csbr/teleport.mdl
sound/deathrun_barbie_csbr/barbiegirl.wav
gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
