maps/k_sci-fi.res
maps/k_sci-fi.bsp
maps/k_sci-fi.txt
models/krumas_be_lapu.mdl
models/bush16.mdl
sound/ambience/electric_hum2.wav
sound/ambience/blzetunnel.wav
sound/ambience/dj_voltage02.wav
sound/ambience/generator.wav
gfx/env/day757bk.tga
gfx/env/day757dn.tga
gfx/env/day757ft.tga
gfx/env/day757lf.tga
gfx/env/day757rt.tga
gfx/env/day757up.tga