maps/kz_satomi.res
maps/kz_satomi.txt
gfx/env/desert01bk.tga
gfx/env/desert01dn.tga
gfx/env/desert01ft.tga
gfx/env/desert01lf.tga
gfx/env/desert01rt.tga
gfx/env/desert01up.tga
models/satomi/bush14.mdl
models/satomi/bush_fern_small.mdl
models/satomi/bush_japan_fern_01.mdl
models/satomi/butterfly.mdl
models/satomi/dao_statue02.mdl
models/satomi/flower.mdl
models/satomi/forge_tree1.mdl
models/satomi/shogun_tourou.mdl
models/satomi/torch.mdl
models/satomi/tree01.mdl
models/satomi/tree_japan_maple_orange.mdl
models/satomi/tree_japan_maple_red.mdl
models/satomi/vamp_gong.mdl
sprites/satomi/flames.spr
sprites/satomi/satomiglowdown.spr
sprites/spr1n/digits/kzblt/x0.spr
sprites/spr1n/digits/kzblt/x1.spr
sprites/spr1n/digits/kzblt/x2.spr
sprites/spr1n/digits/kzblt/x3.spr
sprites/spr1n/digits/kzblt/x4.spr
sprites/spr1n/digits/kzblt/x5.spr
sprites/spr1n/digits/kzblt/x6.spr
sprites/spr1n/digits/kzblt/x7.spr
sprites/spr1n/digits/kzblt/x8.spr
sprites/spr1n/digits/kzblt/x9.spr
sound/satomi/tree_room.wav
sound/satomi/windyforest.wav