maps/surf_ski_2.bsp
maps/surf_ski_2.res
sound/misc/headshot.wav
sound/misc/impressive.wav
sound/misc/perfect.wav
sound/misc/doublekill.wav
sound/misc/multikill.wav
sound/misc/monsterkill.wav
sound/misc/killingspree.wav
sound/misc/dominating.wav
sound/misc/godlike.wav
sound/misc/firstblood.wav
sound/misc/takenlead.wav
sound/misc/lostlead.wav
sound/misc/tiedlead.wav
sound/misc/payattention.wav
sound/misc/humiliation.wav
sound/misc/prepare.wav
sound/misc/becomeone.wav
sound/misc/doh.wav
sound/misc/excellent.wav
sound/misc/force2.wav
sound/misc/feelgood.wav
sound/misc/bell.wav
sound/misc/ochnoe.wav
sound/misc/awwman.wav
sound/misc/kenny1.wav
sound/misc/nanu.wav
